query getFeatured1($slug: String) {
  category(id: 5) {
    articles(where: { slug: $slug }) {
      id
      slug
      title
      content
      excerpt
      created_at
      author {
        username
      }
      image {
        url
      }
    }
    name
    id
  }
}